language: go
dist: trusty
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t samihan/go_webapp .
    - docker images
    - docker push samihan/go_webapp
  - stage: Deploy to Heroku
    deploy:
      provider: heroku
      api_key:
        secure: 4d8d72cb-4ab9-4e69-850e-096efc8e968f
      skip_cleanup: true
