language: go
dist: trusty
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t samihan/go_webapp .
    - docker images
    - docker push samihan/go_webapp
  - stage: Deploy to Heroku
    deploy:
      provider: heroku
      api_key:
        secure: "TWU7ZTUIFhN1/9wF6ITvQ+9m82fExRHaPitqyVWxfXBMlrK50KAKNxKMRTekDS19ZuIxMAnkCLpB9tdlWTJfq2UnBIV8tOW4hXrojbXiVY7n8lttRKMeJNzD2dlOJ0wike43flEVS5zGeNIy4uLopmrLW193SLcf4/WnQhuo1AbJ4UiX40wgpL8+167ia1D9g3JR0uRsH2npVIvCgdNCb9ImNefzng+ayyMpzFPwGxKJ462uHAd8PH9zQjtQqs1fcuQ2JTBEj0nu1rYrELdVyvYFLDAWcxGyhkmV2yjhKQR2E+i+w3HPgJsBmEGO5PSJYkQy00/sKPen/eihgOgfMjXtAdke17fswb2WJ4VTfi95OCWyUxwsQkmNcrLO05kG/XtOWgo/Mk4dpoFmlh2F9Do8LVXw7ivE572WmhEK8XGIN3ZZ2FhfWomYm+yzkslR/DHW1rBab2swy9GikjVnWxx/GFHYkqkmCX5cYaah/3JB1hIb0Ou60l+F8fTXPVo85iVTngFB4PoA45s3EAwEMn0m9zvRUawehbxribtoasHXD4JFqYWJYdrYNAjx8gdr6spMWg5fj5JRRM+OMyKnUv6/Eo896jFjiuD8nw9xJkhv/OzJ3gH/Q9NuKkpok5CunsUf8mGFH0u95RoqbVVw1gju6DfU/1HCGJgCzAoq8IY="
